# ============================================================================
# APPLICATION CONTROLLER (Deployment)
# ============================================================================
# Manages the lifecycle of the Postgres container.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1 # Always keep exactly one Postgres instance running
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      enableServiceLinks: false
      containers:
      - name: postgres
        image: oauth.postgres:dev # docker image
        imagePullPolicy: Never 
        ports:
        - containerPort: 5432
        # Runtime configuration (Overrides Dockerfile defaults)
        env:
        - name: POSTGRES_DB
          value: "oauth"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        # Mapping internal paths to external volumes
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # Where Postgres saves data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d # Where initialization SQLs go
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc # Connect to the "Storage Reservation" above
      - name: init-scripts
        configMap:
          name: postgres-init-sql # Connect to the ConfigMap containing your SQLs
