apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # only one node can write to this disk at a time
  resources:
    requests:
      storage: 1Gi # requesting 1GB of persistent storage
