apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # external port for the cluster
      targetPort: 5432 # internal port on the container
