apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      enableServiceLinks: false
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
